version: '3'


services:

  # Core services
  audio:
    build: ./core/audio
    privileged: true
    labels:
      io.balena.features.dbus: 1

  multiroom-client:
    build: ./core/multiroom/client
    restart: on-failure

  # Plugins
  # bluetooth:
  #   build: ./plugins/bluetooth
  #   restart: on-failure
  #   network_mode: host
  #   cap_add:
  #     - NET_ADMIN
  #   labels:
  #     io.balena.features.dbus: 1
